const USER_ROLES = {
  CUSTOMER: "CUSTOMER",
  RIDER: "RIDER",
  ADMIN: "ADMIN"
}

const ACCOUNT_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED"
}

const RIDER_AVAILABILITY = {
  AVAILABLE: "AVAILABLE",
  BUSY: "BUSY",
  OFFLINE: "OFFLINE"
}

const DELIVERY_STATUS = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  ASSIGNED: "ASSIGNED",
  PICKED_UP: "PICKED_UP",
  IN_TRANSIT: "IN_TRANSIT",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED"
}

const PAYMENT_METHODS = {
  CASH: "CASH",
  CARD: "CARD",
  TRANSFER: "TRANSFER"
}

const PAYMENT_STATUS = {
  PENDING: "PENDING",
  SUCCESSFUL: "SUCCESSFUL",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED"
}

const PACKAGE_TYPES = {
  DOCUMENTS: "DOCUMENTS",
  PARCEL: "PARCEL",
  FOOD: "FOOD",
  FRAGILE: "FRAGILE",
  ELECTRONICS: "ELECTRONICS",
  BOX: "BOX",
  OTHER: "OTHER"
}

const VEHICLE_TYPES = {
  BICYCLE: "BICYCLE",
  MOTORCYCLE: "MOTORCYCLE",
  CAR: "CAR",
  VAN: "VAN"
}

// Allowed state transitions for delivery lifecycle
const VALID_DELIVERY_TRANSITIONS = {
  [DELIVERY_STATUS.PENDING]: [DELIVERY_STATUS.CONFIRMED, DELIVERY_STATUS.CANCELLED],
  [DELIVERY_STATUS.CONFIRMED]: [DELIVERY_STATUS.ASSIGNED, DELIVERY_STATUS.CANCELLED],
  [DELIVERY_STATUS.ASSIGNED]: [DELIVERY_STATUS.PICKED_UP, DELIVERY_STATUS.CONFIRMED, DELIVERY_STATUS.CANCELLED],
  [DELIVERY_STATUS.PICKED_UP]: [DELIVERY_STATUS.IN_TRANSIT],
  [DELIVERY_STATUS.IN_TRANSIT]: [DELIVERY_STATUS.DELIVERED],
  [DELIVERY_STATUS.DELIVERED]: [],
  [DELIVERY_STATUS.CANCELLED]: []
}

module.exports = {
  USER_ROLES,
  ACCOUNT_STATUS,
  RIDER_AVAILABILITY,
  DELIVERY_STATUS,
  PAYMENT_METHODS,
  PAYMENT_STATUS,
  PACKAGE_TYPES,
  VEHICLE_TYPES,
  VALID_DELIVERY_TRANSITIONS
}
